# Generated by Django 3.1.1 on 2020-09-17 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=1000, null=True)),
                ('average_vote', models.CharField(max_length=20)),
                ('user_rating', models.IntegerField(max_length=10, null=True)),
                ('user_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
