# Generated by Django 3.1.1 on 2020-09-17 02:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movieservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
