# Generated by Django 3.1.1 on 2020-09-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieservice', '0002_auto_20200917_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='user_rating',
            field=models.IntegerField(null=True),
        ),
    ]
