# Generated by Django 3.1.1 on 2020-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieservice', '0003_auto_20200917_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='average_vote',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
